name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "**.md"
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker tag
      id: vars
      run: echo "TAG=$(date +'%d-%m-%y')" >> $GITHUB_ENV

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ghcr.io/${{ github.repository_owner }}/smartarts:${{ env.TAG }}
        docker build . --file Dockerfile --tag ghcr.io/${{ github.repository_owner }}/smartarts:latest

    - name: Push the Docker image
      run: |
        docker push ghcr.io/${{ github.repository_owner }}/smartarts:${{ env.TAG }}
        docker push ghcr.io/${{ github.repository_owner }}/smartarts:latest
